name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish FGE.Console -c Release -r win-x64 --self-contained
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/home/runner/work/FG-Exporter/FG-Exporter/FGE.Console/bin/Release/net6.0/win-x64/publish/fge.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
