name: Publish Release

on:
  workflow_run:
    workflows: [Add Version Tag]
    types:
      - completed
    branches:
      - main

jobs:        
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Get Version Tag
      id: get_version
      uses: johngeorgewright/parse-version-action@v1.0.2
      with:
        ref: ${{ github.ref }}
        trim-start: v
    - name: Echo Tag
      run: echo ${{ steps.parser.outputs.version }}.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish FGE.Console -c Release -r win-x64 --self-contained /p:AssemblyVersion=${{ steps.parser.outputs.version }}.0
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/home/runner/work/FG-Exporter/FG-Exporter/FGE.Console/bin/Release/net6.0/win-x64/publish/fge.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
