name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Get Version Tag
      uses: battila7/get-version-action@v2
      id: get_version        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Set Version
      uses: SiqiLu/dotnet-bump-version@master
      with:
        version_files: "**/*.csproj"
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: dotnet publish FGE.Console -c Release -r win-x64 --self-contained /p:AssemblyVersion=${{ steps.get_version.outputs.version-without-v }}
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/home/runner/work/FG-Exporter/FG-Exporter/FGE.Console/bin/Release/net6.0/win-x64/publish/fge.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
